#!/bin/sh

export TEMP_DIR="$(mktemp -d)"

if [ ! -f "${OPENVPN_CONFIG_FILE}" ] ; then
    echo "No OpenVPN config. Exiting."
    exit 1
fi

# Add ovpn user/pass
if ! [ -z ${OPENVPN_USERNAME} ]; then
    echo "$OPENVPN_USERNAME" >"${TEMP_DIR}/openvpn-credentials.txt"
    echo "$OPENVPN_PASSWORD" >>"${TEMP_DIR}/openvpn-credentials.txt"
    chmod 600 "${TEMP_DIR}/openvpn-credentials.txt"

    if [ "${OPENVPN_AUTO_CONFIG}" == "true" ]; then
        grep -v "auth-user-pass" <"${OPENVPN_CONFIG_FILE}" >"${TEMP_DIR}/config.ovpn"
        echo "auth-user-pass ${TEMP_DIR}/openvpn-credentials.txt" >>"${TEMP_DIR}/config.ovpn"
    fi
fi

if [ ! -f "${TEMP_DIR}/config.ovpn" ]; then
    cp "${OPENVPN_CONFIG_FILE}" "${TEMP_DIR}/config.ovpn"
fi

openvpn --config "${TEMP_DIR}/config.ovpn"
